import { Jost } from "next/font/google";
import "./globals.css";

const jostFont = Jost({
  variable: "--font-jost",
  subsets: ["latin"],
});


export const metadata = {
  title: "Suruchi | Home ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon.png" />
      </head>
      <body
        className={`${jostFont.variable}  antialiased  `}
      >
        {children}
      </body>
    </html>
  );
}



